// <auto-generated />
using System;
using Entities.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7417dd6-ab9e-4b55-8ccb-e5fe28cf236a"),
                            Name = "Philistine"
                        },
                        new
                        {
                            Id = new Guid("51b7ab30-2365-4e53-8136-6e2ea26fe139"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("49e3b79b-2403-4d02-9067-2ceb2cf39251"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("5dd646d9-8ccb-4801-bfe8-d41881b0a656"),
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("66111b49-5cd9-4d8f-99f8-db6c04d5e432"),
                            Name = "Yaman"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool?>("ReceiveNewsLetters")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("persons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("116f8e3d-c396-4759-8e45-ba7823d656a3"),
                            Address = "Kareli, Allahabad, U.P.",
                            CountryId = new Guid("c7417dd6-ab9e-4b55-8ccb-e5fe28cf236a"),
                            DateOfBirth = new DateTime(2002, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "imakhlaqxd@gmail.com",
                            Gender = "Male",
                            Name = "Akhlaq Ahmad",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("e967510e-37cf-4aa5-8b3f-10d5389e6ebc"),
                            Address = "Kareli, Allahabad, U.P.",
                            CountryId = new Guid("c7417dd6-ab9e-4b55-8ccb-e5fe28cf236a"),
                            DateOfBirth = new DateTime(2006, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "imakhlaqxd22@gmail.com",
                            Gender = "Male",
                            Name = "Dilshad Ahmad",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("46f98771-9622-4e27-a160-d4941bed238a"),
                            Address = "2No Adda, Siwan, Bihar",
                            CountryId = new Guid("66111b49-5cd9-4d8f-99f8-db6c04d5e432"),
                            DateOfBirth = new DateTime(2000, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "imakhlaqxd123@gmail.com",
                            Gender = "Male",
                            Name = "Yusuf Kamal",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("ad57c271-c77c-4a14-965c-5dca5695ed1d"),
                            Address = "M.M Coloney, Siwan, Bihar",
                            CountryId = new Guid("5dd646d9-8ccb-4801-bfe8-d41881b0a656"),
                            DateOfBirth = new DateTime(2010, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "imakhlaqxd122@gmail.com",
                            Gender = "Male",
                            Name = "Abdullah Bin Tahir",
                            ReceiveNewsLetters = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
