#this is an api gateway
spring:
  application:
    name: api-service
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8081
          predicates:
            - Path=/books/**
          filters:
            - TokenRelay # Token relay filter appends the oauth (or jwt) token to request header before forwarding requests
  security:
    oauth2:
      client:
        provider:
          platform-auth-server:
            issuer-uri: http://127.0.0.1:9000
        registration:
          gateway-client:
            provider: platform-auth-server
            client-id: gateway-client
            client-secret: "secret"
            client-authentication-method: client_secret_basic
            authorization-grant-type:
              - authorization_code
              - refresh_token
            redirect-uri: http://localhost:8080/login/oauth2/code/gateway-client
            scope:
              - openid
              - profile
              - email
# application.yml