#Database
POSTGRES_USERNAME: user
POSTGRES_PASSWORD: letmein
POSTGRES_HOST: 127.0.0.1
POSTGRES_DATABASE: docdatabase
POSTGRES_PORT: 5432

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

#Email config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID:
EMAIL_PASSWORD:
VERIFY_EMAIL_HOST: http://localhost:8085


#JWT
JWT_EXPIRATION: 432_000_000
JWT_SECRET: ${JWT_SECRET} # will be passed through the environment