services:
  db:
    container_name: postgres
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /.data/postgres
      POSTGRES_DB: bank
    volumes:
      - db:/.data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: always
networks:
  db:
    driver: bridge

volumes:
  db: